import {nextStep} from './journey';
import type {Journey} from './journey';
export type Area = 'base'|'career'|'contracts'|'body'|'studio'|'life';
export type Energy = 'low'|'medium'|'high';
export type Reason = 'energy'|'size'|'clarity'|'avoidance'|'time'|'waiting'|'obsolete';
export type Mission = {id:string;area:Area;title:string;why:string;first:string;done:string;minutes:number;energy:Energy;xp:number;smaller:string[];impact:number;requires?:string;kind?:'review'|'return'|'taxi';};
export type History = {id:string;at:string;status:'done'|'missed'|'obsolete';reason?:Reason;small?:boolean};
export type State = {schemaVersion:1;onboarded:boolean;name:string;chapter:number;energy:Energy;focus:'hard'|'usual'|'easy';minutes:number;checkinDate:string;lastSeen:string;startedAt?:string;review14?:{start:string;finish:string;pressure:string;time:string;return:string};returning:boolean;started:string|null;smallSteps:Record<string,number>;history:History[];xp:Record<Area,number>;achievements:string[];directions:Record<Area,boolean>;money:{received:number;expenses:number;expected:number};real:{contacts:number;interviews:number;releases:number;movement:number};notes:{at:string;event:string;thought:string;feeling:string;action:string;balanced:string;next:string}[];projectReady:boolean;reviewDismissed:boolean;journey?:Journey;};
export const areas:Record<Area,{name:string;short:string}>={base:{name:'База',short:'База'},career:{name:'Деловой центр',short:'Карьера'},contracts:{name:'Контракты',short:'Деньги'},body:{name:'Тренировочная площадка',short:'Форма'},studio:{name:'Студия',short:'Студия'},life:{name:'Город',short:'Город'}};
export const missions:Mission[]=[
 {id:'career_contact',area:'career',title:'Написать одному человеку по работе',why:'Так ты проверишь ещё один канал поиска, помимо откликов. Ответ человека не зависит от тебя.',first:'Открой чат с человеком, которому уместно написать, и сформулируй одну конкретную просьбу.',done:'Сообщение отправлено.',minutes:15,energy:'low',xp:28,smaller:['Выбери одного человека и запиши, зачем хочешь ему написать.','Открой подходящий чат.'],impact:9},
 {id:'career_vacancy',area:'career',title:'Проверить одну вакансию',why:'Сравни её задачи и условия со своими критериями. Откликаться сейчас не обязательно.',first:'Открой одну вакансию и отметь два совпадения или расхождения.',done:'Вакансия сохранена для следующего шага или отклонена с понятной причиной.',minutes:15,energy:'low',xp:18,smaller:['Открой одну вакансию, не принимая решения.'],impact:7},
 {id:'career_case',area:'career',title:'Записать один рабочий пример',why:'На собеседовании легче говорить о конкретном случае, чем подбирать общие слова о себе.',first:'Выбери один случай и запиши: какая была задача, что сделал именно ты, какой результат известен.',done:'Есть короткий рассказ без придуманных цифр: ситуация, действие, результат.',minutes:30,energy:'medium',xp:35,smaller:['Назови один случай, который можно разобрать позже.','Открой заметку для этого случая.'],impact:8},
 {id:'career_direction',area:'career',title:'Назвать подходящую роль',why:'Два обязательных условия помогут быстро отсекать вакансии, на которые не стоит тратить время.',first:'Запиши одну желаемую роль и два условия, без которых она тебе не подходит.',done:'У тебя записаны роль и два условия.',minutes:15,energy:'low',xp:18,smaller:['Запиши только тип роли.'],impact:9},
 {id:'career_network',area:'career',title:'Выбрать одного подходящего человека',why:'Уместное обращение начинается с понимания, зачем ты пишешь именно ему.',first:'Назови человека из профессионального круга и одну конкретную тему для разговора.',done:'Выбран человек и цель сообщения.',minutes:10,energy:'low',xp:14,smaller:['Вспомни имя одного человека.'],impact:8},
 {id:'career_review',area:'career',title:'Проверить маршрут',why:'Если усилия не дают продолжения, стоит изменить подход.',first:'Посмотри последние пять откликов или контактов.',done:'Выбрано одно изменение в поиске.',minutes:30,energy:'medium',xp:32,smaller:['Открой один недавний отклик.','Найди место, где хранится история откликов.'],impact:10,kind:'review'},
 {id:'contract_step',area:'contracts',title:'Закрыть одну договорённость по проекту',why:'Проект движется, когда согласованный материал готов или отправлен. Само открытие папки — только подготовка.',first:'Посмотри, какой один материал или ответ от тебя ждут сейчас, и сделай именно его.',done:'Один согласованный материал завершён или отправлен.',minutes:30,energy:'medium',xp:32,smaller:['Запиши, какой материал или ответ от тебя ждут.','Открой материалы действующего проекта.'],impact:8},
 {id:'contract_audit',area:'contracts',title:'Проверить одну действующую договорённость',why:'Сначала выясни актуальный статус, чтобы не брать в работу уже закрытый этап.',first:'Открой последнюю переписку по одному проекту и отметь: кто ждёт следующего действия?',done:'Текущий статус и следующий ответственный понятны.',minutes:15,energy:'low',xp:17,smaller:['Назови один действующий проект.'],impact:8},
 {id:'contract_money',area:'contracts',title:'Записать один проверенный денежный факт',why:'Полученные деньги, расходы и ожидания лучше видеть отдельно: обещание оплаты ещё не поступление.',first:'Открой банковское приложение или документ и проверь одну сумму. Затем внеси её в «Инструменты».',done:'Одна проверенная сумма записана в нужной строке или подтверждено, что данных пока нет.',minutes:10,energy:'low',xp:12,smaller:['Выбери сумму, которую нужно проверить.'],impact:7},
 {id:'contract_followup',area:'contracts',title:'Напомнить о договорённости',why:'Не потерять возможность из-за паузы в переписке.',first:'Выбери разговор, где уже уместно напомнить о себе.',done:'Сообщение отправлено.',minutes:15,energy:'low',xp:24,smaller:['Выбери один разговор.','Вспомни, кому можно напомнить о себе.'],impact:8},
 {id:'taxi_plan',area:'contracts',title:'Проверить окно для смены',why:'Выходить только на полноценную и безопасную смену.',first:'Проверь, есть ли 7–8 часов с учётом дороги и отдыха.',done:'Смена запланирована или спокойно отклонена.',minutes:10,energy:'medium',xp:15,smaller:['Посмотри доступное время и силы.'],impact:5,kind:'taxi'},
 {id:'body_walk',area:'body',title:'Выйти на прогулку',why:'Немного движения без требования идеальной тренировки.',first:'Надень обувь и выйди из дома.',done:'Прогулка состоялась.',minutes:20,energy:'low',xp:20,smaller:['Выйди на пять минут.'],impact:6},
 {id:'body_prepare',area:'body',title:'Подготовить одежду для прогулки',why:'Когда одежда или обувь под рукой, легче выйти без дополнительных сборов.',first:'Положи удобную одежду или обувь туда, где увидишь её перед выходом.',done:'Одежда или обувь для выхода готовы.',minutes:10,energy:'low',xp:14,smaller:['Выбери, что наденешь для выхода.'],impact:5},
 {id:'base_food',area:'base',title:'Позаботиться о еде',why:'Поддержать себя простым реальным действием.',first:'Выбери самый простой доступный вариант еды.',done:'Еда приготовлена или собрана.',minutes:15,energy:'low',xp:12,smaller:['Посмотри, что уже есть из еды.'],impact:5},
 {id:'base_tomorrow',area:'base',title:'Подготовить одну вещь для утра',why:'Утром не придётся искать её или решать, что взять.',first:'Выбери вещь, которая точно понадобится завтра, и положи её на видное место.',done:'Одна конкретная вещь лежит на месте.',minutes:10,energy:'low',xp:12,smaller:['Назови одну вещь, которая понадобится завтра.'],impact:5},
 {id:'base_sleep',area:'base',title:'Убрать одну помеху перед сном',why:'Не нужно менять весь режим. Достаточно облегчить сегодняшний вечер.',first:'Выбери одну помеху — свет, шум или незакрытое мелкое дело — и убери её.',done:'Одна выбранная помеха убрана.',minutes:10,energy:'low',xp:12,smaller:['Назови одну помеху, которую можно убрать.'],impact:5},
 {id:'studio_finish',area:'studio',title:'Закрыть одну недоделанную часть',why:'Делай ту часть выбранного материала, которая мешает назвать его готовым.',first:'Открой выбранный материал, назови одну недоделанную часть и закончи её.',done:'Эта часть завершена и сохранена.',minutes:30,energy:'medium',xp:30,smaller:['Назови одну недоделанную часть.','Открой выбранный материал.'],impact:7},
 {id:'studio_ready',area:'studio',title:'Проверить итоговый файл',why:'До решения о публикации проверь, что файл открывается и содержит нужную версию.',first:'Открой итоговый файл от начала до конца и запиши одну оставшуюся правку, если она нужна.',done:'Файл проверен; решение о публикации остаётся за тобой.',minutes:20,energy:'medium',xp:28,smaller:['Проверь, открывается ли файл.'],impact:7},
 {id:'studio_select',area:'studio',title:'Выбрать работу для завершения',why:'Когда одновременно открыто несколько проектов, полезно явно выбрать один ближайший к готовности.',first:'Посмотри список начатого и назови один материал, у которого осталось меньше всего работы.',done:'Один материал выбран, следующая недоделанная часть названа.',minutes:10,energy:'low',xp:12,smaller:['Открой папку с начатыми работами.'],impact:7},
 {id:'body_repeat',area:'body',title:'Выбрать следующий выход',why:'План должен подходить реальному расписанию, иначе он быстро становится лишним давлением.',first:'Посмотри на ближайшие дни и выбери одно удобное окно для прогулки.',done:'Один реалистичный момент выбран.',minutes:10,energy:'low',xp:12,smaller:['Назови день, когда могло бы получиться.'],impact:5},
 {id:'life_idea',area:'life',title:'Записать одну приятную идею',why:'Идея может остаться идеей; здесь не нужно отчитываться о свободном времени.',first:'Запиши одно простое занятие, которое тебе действительно хочется.',done:'Одна идея записана.',minutes:10,energy:'low',xp:0,smaller:['Просто назови идею.'],impact:4},
 {id:'life_invite',area:'life',title:'Предложить удобный вариант',why:'Другому человеку проще ответить на конкретное предложение. Отказ или перенос — нормальный исход.',first:'Напиши одному человеку, что ты хотел бы сделать, и предложи удобный день.',done:'Предложение отправлено.',minutes:10,energy:'low',xp:0,smaller:['Составь черновик предложения.'],impact:4},
 {id:'life_plan',area:'life',title:'Уточнить совместный план',why:'Договорённость должна устраивать обоих; приложение не оценивает отношения.',first:'Если ответ уже есть, уточни время или место. Если нет, оставь разговор без напоминания.',done:'План согласован или спокойно отложен.',minutes:10,energy:'low',xp:0,smaller:['Проверь, есть ли ответ.'],impact:4},
 {id:'return_step',area:'base',title:'Продолжить с малого',why:'Вернуться после паузы без попытки наверстать всё.',first:'Выбери одну небольшую вещь, которую можно сделать сейчас.',done:'Один доступный шаг сделан.',minutes:10,energy:'low',xp:12,smaller:['Открой нужный материал или место.'],impact:10,kind:'return'}
];
export const today=()=>new Date().toLocaleDateString('sv-SE');
export const dayOf=(iso:string)=>new Date(iso).toLocaleDateString('sv-SE');
export const freshState=():State=>({schemaVersion:1,onboarded:false,name:'',chapter:0,energy:'medium',focus:'usual',minutes:30,checkinDate:'',lastSeen:new Date().toISOString(),startedAt:new Date().toISOString(),returning:false,started:null,smallSteps:{},history:[],xp:{base:0,career:0,contracts:0,body:0,studio:0,life:0},achievements:[],directions:{base:true,career:true,contracts:true,body:true,studio:true,life:true},money:{received:0,expenses:0,expected:0},real:{contacts:0,interviews:0,releases:0,movement:0},notes:[],projectReady:false,reviewDismissed:false});
export const reviewDue=(s:State,now=new Date())=>Boolean(s.onboarded&&!s.review14&&s.startedAt&&daysAway(s.startedAt,now)>=14);
export function totalXp(s:State){return Object.values(s.xp).reduce((a,b)=>a+b,0)}
export function daysAway(lastSeen:string,now=new Date()){return Math.floor((now.getTime()-new Date(lastSeen).getTime())/86400000)}
export function needsReview(s:State){const careerDone=s.history.filter(h=>h.status==='done'&&['career_contact','career_vacancy'].includes(h.id)).length;return careerDone>=5&&s.real.interviews===0&&!s.reviewDismissed}
export function chooseMissions(s:State):{primary:Mission|null;sides:Mission[];doneToday:boolean}{
 const doneToday=s.history.filter(h=>h.status==='done'&&dayOf(h.at)===today()).length;
 if(doneToday>=3)return {primary:null,sides:[],doneToday:true};
 const usedToday=new Set(s.history.filter(h=>dayOf(h.at)===today()&&!(['size','clarity','avoidance','energy','time'].includes(h.reason||''))).map(h=>h.id));
 const energyRank={low:0,medium:1,high:2};
 if(s.journey){
  const candidates=s.journey.goals.map((id,priority)=>({mission:nextStep(s,id),priority})).filter((v):v is {mission:NonNullable<typeof v.mission>;priority:number}=>Boolean(v.mission)).map(v=>({mission:missions.find(m=>m.id===v.mission.mission),priority:v.priority})).filter((v):v is {mission:Mission;priority:number}=>Boolean(v.mission)&&!usedToday.has(v.mission!.id)).sort((a,b)=>a.priority-b.priority);
  const available=candidates.filter(({mission})=>mission.minutes<=s.minutes&&energyRank[mission.energy]<=energyRank[s.energy]);
  const selected=available.length?available:candidates.filter(({mission})=>mission.smaller.length>0);
  const primary=selected[0]?.mission??null;
  return {primary,sides:selected.slice(1,3).map(v=>v.mission),doneToday:false};
 }
 const candidates=missions.filter(m=>!usedToday.has(m.id)&&s.directions[m.area]&&m.minutes<=s.minutes&&energyRank[m.energy]<=energyRank[s.energy]&&(!m.requires||Boolean(s[m.requires as 'projectReady']))&&(m.kind!=='return'||s.returning)&&(m.kind!=='review'||needsReview(s)));
 const scored=candidates.map(m=>{const misses=s.history.filter(h=>h.id===m.id&&h.status==='missed').slice(-2);const latest=s.history.filter(h=>h.id===m.id).at(-1);let score=m.impact*3+(m.area==='career'?5:0)+(m.area==='contracts'?4:0)+(s.energy==='low'&&m.area==='base'?20:0)+(m.kind==='return'?30:0)+(m.kind==='review'?32:0)-(misses.length*13)-(latest?.status==='done'?8:0)-(s.focus==='hard'&&m.minutes>15?8:0)+(latest?.status==='missed'&&['size','clarity','avoidance'].includes(latest.reason||'')?38:0);if(s.started===m.id)score+=100;return {m,score}}).sort((a,b)=>b.score-a.score||a.m.id.localeCompare(b.m.id));
 const primary=scored[0]?.m??null;
 const sides=scored.filter(x=>x.m.id!==primary?.id&&x.m.area!==primary?.area).slice(0,2).map(x=>x.m);
 return {primary,sides,doneToday:false};
}
export function recommendedSmall(s:State,m:Mission){return s.smallSteps[m.id]||((m.minutes>s.minutes||({low:0,medium:1,high:2}[m.energy]>{low:0,medium:1,high:2}[s.energy]))&&m.smaller.length?1:0)}
export function complete(s:State,m:Mission):State{const at=new Date().toISOString();const small=Boolean(s.smallSteps[m.id]);const xp={...s.xp,[m.area]:s.xp[m.area]+(m.xp===0?0:small?Math.max(8,Math.round(m.xp*.6)):m.xp)};const history=[...s.history,{id:m.id,at,status:'done' as const,small}];const real={...s.real};if(!small&&(m.id==='career_contact'||m.id==='contract_followup'))real.contacts++;if(m.id==='body_walk')real.movement++;const achievements=[...s.achievements];const add=(v:string)=>{if(!achievements.includes(v))achievements.push(v)};if(history.filter(h=>h.status==='done').length===1)add('Первый ход');if(s.returning)add('С возвращением');if(s.energy==='low'&&m.area!=='base')add('Несмотря ни на что');if(m.kind==='review')add('Смена курса');if(m.id==='studio_finish')add('Доведено');if(m.id==='career_contact'&&!small)add('Новая дверь');if(history.filter(h=>h.status==='done'&&dayOf(h.at)===today()).length>=3)add('На сегодня достаточно');const count=history.filter(h=>h.status==='done').length;return {...s,xp,history,real,achievements,returning:false,started:null,smallSteps:{...s.smallSteps,[m.id]:0},chapter:count>=12?2:count>=5?1:0,reviewDismissed:m.kind==='review'?true:s.reviewDismissed}}
export function miss(s:State,m:Mission,reason:Reason):State{const history=[...s.history,{id:m.id,at:new Date().toISOString(),status:reason==='obsolete'?'obsolete' as const:'missed' as const,reason}];const next={...s,history,started:null};if(reason==='energy')return {...next,energy:'low',minutes:Math.min(s.minutes,15)};if(reason==='time')return {...next,minutes:15};if(reason==='size'||reason==='clarity'||reason==='avoidance')return {...next,smallSteps:{...s.smallSteps,[m.id]:Math.min((s.smallSteps[m.id]||0)+1,m.smaller.length)}};return next}
export const reasons:Record<Reason,string>={energy:'Сегодня мало сил',size:'Слишком большая задача',clarity:'Непонятно, с чего начать',avoidance:'Тяжело взяться',time:'Не хватило времени',waiting:'Жду другого человека',obsolete:'Уже не нужно'};
