import test from 'node:test';
import assert from 'node:assert/strict';
import {chooseMissions,complete,freshState,miss,missions,needsReview,reviewDue,totalXp} from './engine';
import {goalProgress,nextStep} from './journey';

test('first visit offers one manageable main mission and at most two alternatives',()=>{const s=freshState();const plan=chooseMissions(s);assert.ok(plan.primary);assert.ok(plan.sides.length<=2);assert.ok(plan.primary!.minutes<=s.minutes)});
test('low energy and short window exclude demanding missions',()=>{const s={...freshState(),energy:'low' as const,minutes:15};const plan=chooseMissions(s);assert.ok(plan.primary);assert.equal(plan.primary!.energy,'low');assert.ok(plan.primary!.minutes<=15);assert.ok(!plan.sides.some(m=>m.energy!=='low'||m.minutes>15))});
test('chosen goal gates later missions behind earlier full steps',()=>{const s=freshState();s.journey={goals:['role'],reason:'',barrier:'unclear',createdAt:new Date(Date.now()-1000).toISOString()};assert.equal(chooseMissions(s).primary?.id,'career_direction');assert.ok(![chooseMissions(s).primary,...chooseMissions(s).sides].some(m=>m?.id==='career_contact'));const next=complete(s,missions.find(m=>m.id==='career_direction')!);assert.equal(nextStep(next,'role')?.mission,'career_vacancy');assert.equal(goalProgress(next,'role').done,1)});
test('a preparatory step stays in the journal but does not close a goal stage',()=>{const s=freshState();s.journey={goals:['network'],reason:'',barrier:'large',createdAt:new Date(Date.now()-1000).toISOString()};s.smallSteps.career_direction=1;const next=complete(s,missions.find(m=>m.id==='career_direction')!);assert.equal(nextStep(next,'network')?.mission,'career_direction');assert.equal(goalProgress(next,'network').done,0)});
test('relationship planning does not grant game experience',()=>{const s=freshState();const next=complete(s,missions.find(m=>m.id==='life_idea')!);assert.equal(totalXp(next),0)});
test('obstacles preserve experience and shrink the next attempt',()=>{const s=freshState();const m=missions[0];const before=totalXp(s);const changed=miss(s,m,'size');assert.equal(totalXp(changed),before);assert.equal(changed.smallSteps[m.id],1);assert.equal(chooseMissions(changed).primary?.id,m.id)});
test('lack of time changes the next choice',()=>{const s={...freshState(),minutes:60};const m=missions.find(m=>m.id==='career_case')!;const changed=miss(s,m,'time');assert.equal(changed.minutes,15);const chosen=chooseMissions(changed).primary;assert.ok(chosen);assert.ok(chosen.minutes<=15)});
test('repeated career actions without an interview prompt review',()=>{const s=freshState();s.energy='high';s.minutes=60;s.history=Array.from({length:5},(_,i)=>({id:'career_contact',at:new Date(Date.now()-(i+1)*86400000).toISOString(),status:'done' as const}));assert.equal(needsReview(s),true);assert.equal(chooseMissions(s).primary?.id,'career_review')});
test('completion adds game experience separately from real action count',()=>{const s=freshState();const m=missions.find(m=>m.id==='career_contact')!;const next=complete(s,m);assert.equal(next.xp.career,m.xp);assert.equal(next.real.contacts,1);assert.equal(next.money.received,0);assert.ok(next.achievements.includes('Первый ход'))});
test('a reduced preparatory step never invents a sent contact',()=>{const s=freshState();const m=missions.find(m=>m.id==='career_contact')!;s.smallSteps[m.id]=1;const next=complete(s,m);assert.ok(next.xp.career>0);assert.equal(next.real.contacts,0);assert.ok(!next.achievements.includes('Новая дверь'))});
test('returning after a pause does not remove progress',()=>{const s=freshState();s.returning=true;s.xp.career=42;s.minutes=15;s.energy='low';const plan=chooseMissions(s);assert.equal(plan.primary?.id,'return_step');assert.equal(totalXp(s),42)});
test('two-week check-in appears once and gives no game reward',()=>{const s=freshState();s.onboarded=true;s.startedAt=new Date(Date.now()-15*86400000).toISOString();assert.equal(reviewDue(s),true);s.review14={start:'Да',finish:'Да',pressure:'Меньше',time:'1–5 минут',return:'Да'};assert.equal(reviewDue(s),false);assert.equal(totalXp(s),0)});
