export type Area = 'base'|'career'|'contracts'|'body'|'studio'|'life';
export type Energy = 'low'|'medium'|'high';
export type Reason = 'energy'|'size'|'clarity'|'avoidance'|'time'|'waiting'|'obsolete';
export type Mission = {id:string;area:Area;title:string;why:string;first:string;done:string;minutes:number;energy:Energy;xp:number;smaller:string[];impact:number;requires?:string;kind?:'review'|'return'|'taxi';};
export type History = {id:string;at:string;status:'done'|'missed'|'obsolete';reason?:Reason;small?:boolean};
export type State = {schemaVersion:1;onboarded:boolean;name:string;chapter:number;energy:Energy;focus:'hard'|'usual'|'easy';minutes:number;checkinDate:string;lastSeen:string;startedAt?:string;review14?:{start:string;finish:string;pressure:string;time:string;return:string};returning:boolean;started:string|null;smallSteps:Record<string,number>;history:History[];xp:Record<Area,number>;achievements:string[];directions:Record<Area,boolean>;money:{received:number;expenses:number;expected:number};real:{contacts:number;interviews:number;releases:number;movement:number};notes:{at:string;event:string;thought:string;feeling:string;action:string;balanced:string;next:string}[];projectReady:boolean;reviewDismissed:boolean;};
export const areas:Record<Area,{name:string;short:string}>={base:{name:'База',short:'База'},career:{name:'Деловой центр',short:'Карьера'},contracts:{name:'Контракты',short:'Деньги'},body:{name:'Тренировочная площадка',short:'Форма'},studio:{name:'Студия',short:'Студия'},life:{name:'Город',short:'Город'}};
export const missions:Mission[]=[
 {id:'career_contact',area:'career',title:'Открыть новую дверь',why:'Один уместный контакт может создать новый путь к работе.',first:'Выбери человека, которому уместно написать по работе.',done:'Сообщение отправлено.',minutes:15,energy:'low',xp:28,smaller:['Выбери одного человека.','Вспомни имя одного подходящего человека.'],impact:9},
 {id:'career_vacancy',area:'career',title:'Найти подходящую роль',why:'Сосредоточиться на вакансии, которая действительно подходит.',first:'Открой одну вакансию и проверь требования.',done:'Подходящая вакансия сохранена или отклонена.',minutes:15,energy:'low',xp:18,smaller:['Открой одну вакансию.'],impact:7},
 {id:'career_case',area:'career',title:'Подготовить сильный пример',why:'На собеседовании будет проще показать свой опыт.',first:'Выбери один реальный рабочий случай с результатом.',done:'Есть короткий рассказ: ситуация, действие, результат.',minutes:30,energy:'medium',xp:35,smaller:['Выбери один случай.','Назови один случай, который стоит вспомнить.'],impact:8},
 {id:'career_review',area:'career',title:'Проверить маршрут',why:'Если усилия не дают продолжения, стоит изменить подход.',first:'Посмотри последние пять откликов или контактов.',done:'Выбрано одно изменение в поиске.',minutes:30,energy:'medium',xp:32,smaller:['Открой один недавний отклик.','Найди место, где хранится история откликов.'],impact:10,kind:'review'},
 {id:'contract_step',area:'contracts',title:'Сдвинуть проект',why:'Продвинуть один действующий проект к оплате или завершению.',first:'Открой текущий проект и проверь его статус.',done:'Один следующий шаг сделан.',minutes:20,energy:'medium',xp:32,smaller:['Открой материалы одного проекта.','Назови один действующий проект.'],impact:8},
 {id:'contract_followup',area:'contracts',title:'Напомнить о договорённости',why:'Не потерять возможность из-за паузы в переписке.',first:'Выбери разговор, где уже уместно напомнить о себе.',done:'Сообщение отправлено.',minutes:15,energy:'low',xp:24,smaller:['Выбери один разговор.','Вспомни, кому можно напомнить о себе.'],impact:8},
 {id:'taxi_plan',area:'contracts',title:'Проверить окно для смены',why:'Выходить только на полноценную и безопасную смену.',first:'Проверь, есть ли 7–8 часов с учётом дороги и отдыха.',done:'Смена запланирована или спокойно отклонена.',minutes:10,energy:'medium',xp:15,smaller:['Посмотри доступное время и силы.'],impact:5,kind:'taxi'},
 {id:'body_walk',area:'body',title:'Выйти на прогулку',why:'Немного движения без требования идеальной тренировки.',first:'Надень обувь и выйди из дома.',done:'Прогулка состоялась.',minutes:20,energy:'low',xp:20,smaller:['Выйди на пять минут.'],impact:6},
 {id:'body_prepare',area:'body',title:'Подготовить тренировку',why:'Завтра будет легче начать.',first:'Подготовь одежду и нужные вещи.',done:'Всё нужное лежит на виду.',minutes:10,energy:'low',xp:14,smaller:['Достань только одежду.'],impact:5},
 {id:'base_food',area:'base',title:'Позаботиться о еде',why:'Поддержать себя простым реальным действием.',first:'Выбери самый простой доступный вариант еды.',done:'Еда приготовлена или собрана.',minutes:15,energy:'low',xp:12,smaller:['Посмотри, что уже есть из еды.'],impact:5},
 {id:'base_tomorrow',area:'base',title:'Упростить утро',why:'Убрать одно лишнее решение на завтра.',first:'Подготовь одну вещь, которая понадобится утром.',done:'Одна вещь готова.',minutes:10,energy:'low',xp:12,smaller:['Выбери только одну вещь.'],impact:5},
 {id:'studio_finish',area:'studio',title:'Довести до результата',why:'Продвинуть уже начатую работу.',first:'Открой материал, который ближе всего к завершению.',done:'Один этап работы завершён.',minutes:30,energy:'medium',xp:30,smaller:['Выбери один материал.','Открой папку с работами.'],impact:7},
 {id:'studio_ready',area:'studio',title:'Подготовить выпуск',why:'Сделать готовую работу доступной людям.',first:'Проверь финальный файл и описание.',done:'Материал готов к публикации.',minutes:20,energy:'medium',xp:28,smaller:['Проверь только финальный файл.'],impact:7,requires:'projectReady'},
 {id:'return_step',area:'base',title:'Продолжить с малого',why:'Вернуться после паузы без попытки наверстать всё.',first:'Выбери одну небольшую вещь, которую можно сделать сейчас.',done:'Один доступный шаг сделан.',minutes:10,energy:'low',xp:12,smaller:['Открой нужный материал или место.'],impact:10,kind:'return'}
];
export const today=()=>new Date().toLocaleDateString('sv-SE');
export const dayOf=(iso:string)=>new Date(iso).toLocaleDateString('sv-SE');
export const freshState=():State=>({schemaVersion:1,onboarded:false,name:'',chapter:0,energy:'medium',focus:'usual',minutes:30,checkinDate:'',lastSeen:new Date().toISOString(),startedAt:new Date().toISOString(),returning:false,started:null,smallSteps:{},history:[],xp:{base:0,career:0,contracts:0,body:0,studio:0,life:0},achievements:[],directions:{base:true,career:true,contracts:true,body:true,studio:true,life:true},money:{received:0,expenses:0,expected:0},real:{contacts:0,interviews:0,releases:0,movement:0},notes:[],projectReady:false,reviewDismissed:false});
export const reviewDue=(s:State,now=new Date())=>Boolean(s.onboarded&&!s.review14&&s.startedAt&&daysAway(s.startedAt,now)>=14);
export function totalXp(s:State){return Object.values(s.xp).reduce((a,b)=>a+b,0)}
export function daysAway(lastSeen:string,now=new Date()){return Math.floor((now.getTime()-new Date(lastSeen).getTime())/86400000)}
export function needsReview(s:State){const careerDone=s.history.filter(h=>h.status==='done'&&['career_contact','career_vacancy'].includes(h.id)).length;return careerDone>=5&&s.real.interviews===0&&!s.reviewDismissed}
export function chooseMissions(s:State):{primary:Mission|null;sides:Mission[];doneToday:boolean}{
 const doneToday=s.history.filter(h=>h.status==='done'&&dayOf(h.at)===today()).length;
 if(doneToday>=3)return {primary:null,sides:[],doneToday:true};
 const usedToday=new Set(s.history.filter(h=>dayOf(h.at)===today()&&!(['size','clarity','avoidance'].includes(h.reason||''))).map(h=>h.id));
 const energyRank={low:0,medium:1,high:2};
 const candidates=missions.filter(m=>!usedToday.has(m.id)&&s.directions[m.area]&&m.minutes<=s.minutes&&energyRank[m.energy]<=energyRank[s.energy]&&(!m.requires||Boolean(s[m.requires as 'projectReady']))&&(m.kind!=='return'||s.returning)&&(m.kind!=='review'||needsReview(s)));
 const scored=candidates.map(m=>{const misses=s.history.filter(h=>h.id===m.id&&h.status==='missed').slice(-2);const latest=s.history.filter(h=>h.id===m.id).at(-1);let score=m.impact*3+(m.area==='career'?5:0)+(m.area==='contracts'?4:0)+(s.energy==='low'&&m.area==='base'?20:0)+(m.kind==='return'?30:0)+(m.kind==='review'?32:0)-(misses.length*13)-(latest?.status==='done'?8:0)-(s.focus==='hard'&&m.minutes>15?8:0)+(latest?.status==='missed'&&['size','clarity','avoidance'].includes(latest.reason||'')?38:0);if(s.started===m.id)score+=100;return {m,score}}).sort((a,b)=>b.score-a.score||a.m.id.localeCompare(b.m.id));
 const primary=scored[0]?.m??null;
 const sides=scored.filter(x=>x.m.id!==primary?.id&&x.m.area!==primary?.area).slice(0,2).map(x=>x.m);
 return {primary,sides,doneToday:false};
}
export function complete(s:State,m:Mission):State{const at=new Date().toISOString();const small=Boolean(s.smallSteps[m.id]);const xp={...s.xp,[m.area]:s.xp[m.area]+(small?Math.max(8,Math.round(m.xp*.6)):m.xp)};const history=[...s.history,{id:m.id,at,status:'done' as const,small}];const real={...s.real};if(!small&&(m.id==='career_contact'||m.id==='contract_followup'))real.contacts++;if(m.id==='body_walk')real.movement++;const achievements=[...s.achievements];const add=(v:string)=>{if(!achievements.includes(v))achievements.push(v)};if(history.filter(h=>h.status==='done').length===1)add('Первый ход');if(s.returning)add('С возвращением');if(s.energy==='low'&&m.area!=='base')add('Несмотря ни на что');if(m.kind==='review')add('Смена курса');if(m.id==='studio_finish')add('Доведено');if(m.id==='career_contact'&&!small)add('Новая дверь');if(history.filter(h=>h.status==='done'&&dayOf(h.at)===today()).length>=3)add('На сегодня достаточно');const count=history.filter(h=>h.status==='done').length;return {...s,xp,history,real,achievements,returning:false,started:null,smallSteps:{...s.smallSteps,[m.id]:0},chapter:count>=12?2:count>=5?1:0,reviewDismissed:m.kind==='review'?true:s.reviewDismissed}}
export function miss(s:State,m:Mission,reason:Reason):State{const history=[...s.history,{id:m.id,at:new Date().toISOString(),status:reason==='obsolete'?'obsolete' as const:'missed' as const,reason}];const next={...s,history,started:null};if(reason==='energy')return {...next,energy:'low',minutes:Math.min(s.minutes,15)};if(reason==='time')return {...next,minutes:15};if(reason==='size'||reason==='clarity'||reason==='avoidance')return {...next,smallSteps:{...s.smallSteps,[m.id]:Math.min((s.smallSteps[m.id]||0)+1,m.smaller.length)}};return next}
export const reasons:Record<Reason,string>={energy:'Сегодня мало сил',size:'Слишком большая задача',clarity:'Непонятно, с чего начать',avoidance:'Тяжело взяться',time:'Не хватило времени',waiting:'Жду другого человека',obsolete:'Уже не нужно'};
