import {useState} from 'react';
import {ArrowRight, Check, ChevronLeft, Compass, Download, Flag, Shield, Sparkles} from 'lucide-react';
import {areas, type Energy, type State} from './engine';
import {barriers, goalOptions, goals, type Barrier, type GoalId, type Journey} from './journey';

type Props={state:State;onDone:(journey:Journey,energy:Energy,minutes:number)=>void;onCancel?:()=>void;onRestore?:(file:File)=>Promise<void>};
export default function JourneySetup({state,onDone,onCancel,onRestore}:Props){
 const [stage,setStage]=useState(0);
 const [selected,setSelected]=useState<GoalId[]>(state.journey?.goals??[]);
 const [reason,setReason]=useState(state.journey?.reason??'');
 const [desiredResult,setDesiredResult]=useState(state.journey?.desiredResult??'');
 const [barrier,setBarrier]=useState<Barrier>(state.journey?.barrier??'unclear');
 const [energy,setEnergy]=useState<Energy>(state.energy);
 const [minutes,setMinutes]=useState(state.minutes);
 const [error,setError]=useState('');
 function toggle(id:GoalId){const area=goals[id].area;setError('');setSelected(current=>current.includes(id)?current.filter(x=>x!==id):current.some(x=>goals[x].area===area)?current.map(x=>goals[x].area===area?id:x):current.length<3?[...current,id]:current)}
 function next(){if(stage===1&&selected.length===0){setError('Выбери хотя бы одно направление.');return}setStage(Math.min(stage+1,4));window.scrollTo(0,0)}
 function back(){setStage(Math.max(stage-1,0));window.scrollTo(0,0)}
 function finish(){const same=state.journey&&selected.length===state.journey.goals.length&&selected.every((id,index)=>id===state.journey!.goals[index]);onDone({goals:selected,reason:reason.trim().slice(0,500),desiredResult:desiredResult.trim().slice(0,300),barrier,createdAt:same?state.journey!.createdAt:new Date().toISOString()},energy,minutes)}
 return <main className="setup"><div className="setup-art" aria-hidden="true"><span className="setup-orbit orbit-one"/><span className="setup-orbit orbit-two"/><span className="setup-beacon">✦</span></div><div className="setup-shell"><header className="setup-header"><span className="setup-brand">L<span>:</span>R <small>LIFE: REBUILD</small></span><span className="setup-count">{stage===0?'НАЧАЛО':`${stage} / 4`}</span></header><div className="setup-body">
 {stage===0&&<><span className="eyebrow">Как здесь всё устроено</span><h1>Сначала цель. Потом шаг.</h1><p className="setup-lead">Ты выбираешь, что хочешь изменить. Игра показывает короткий маршрут, предлагает один шаг за раз и объясняет, зачем он нужен.</p><div className="guide-grid"><div><Compass/><strong>Маршрут</strong><p>Выбери до трёх направлений. Их можно поменять позже.</p></div><div><Flag/><strong>Один шаг</strong><p>Начни с действия, которое помещается в сегодняшний день. Не подходит — уменьши или пропусти.</p></div><div><Sparkles/><strong>Честный прогресс</strong><p>На экране видно, какие этапы пройдены. Опыт не равен деньгам и не исчезает после паузы.</p></div></div><p className="setup-nav-help"><strong>Где что искать:</strong> «Игра» — следующий шаг, «План» — путь к цели, «Карта» — районы, «Записи» — деньги и мысли, «Профиль» — настройки и копия.</p><p className="setup-note"><Shield size={17}/> Записи остаются на этом устройстве. Перед сменой телефона скачай копию в профиле.</p>{onRestore&&!state.onboarded&&<label className="setup-restore"><Download size={17}/> Восстановить прежнюю копию<input type="file" accept="application/json,.json" hidden onChange={async e=>{const file=e.target.files?.[0];if(file)try{await onRestore(file)}catch(err){setError(err instanceof Error?err.message:'Не удалось открыть копию.')}e.target.value=''}}/></label>}{error&&<p role="alert" className="form-error">{error}</p>}</>}
 {stage===1&&<><span className="eyebrow">Твои направления</span><h1>Что сейчас важнее?</h1><p className="setup-lead">Выбери от одного до трёх результатов. Порядок важен: первый получит приоритет в предложениях.</p><div className="goal-picker">{goalOptions.map(goal=><button type="button" className={`goal-option ${selected.includes(goal.id)?'selected':''}`} key={goal.id} onClick={()=>toggle(goal.id)} aria-pressed={selected.includes(goal.id)}><span className="goal-option-icon">{selected.includes(goal.id)?<Check size={18}/>:<span/>}</span><span><small>{areas[goal.area].name}</small><strong>{goal.title}</strong><em>{goal.result}</em></span></button>)}</div><p className="setup-tip">Если выбрать два варианта в одном районе, новый заменит прежний. Остальные направления можно добавить позже.</p>{error&&<p role="alert" className="form-error">{error}</p>}</>}
 {stage===2&&<><span className="eyebrow">Смысл и помеха</span><h1>Чего ты хочешь добиться?</h1><label className="setup-field">Какой реальный результат ты хочешь увидеть?<textarea rows={2} maxLength={300} value={desiredResult} placeholder="Например: получить приглашение на разговор по подходящей роли" onChange={e=>setDesiredResult(e.target.value)}/></label><label className="setup-field">Почему это важно тебе сейчас?<textarea rows={2} maxLength={500} value={reason} placeholder="Можно оставить пустым" onChange={e=>setReason(e.target.value)}/></label><p className="setup-lead">Что чаще всего мешает первому шагу?</p><div className="barrier-grid">{(Object.keys(barriers) as Barrier[]).map(id=><button type="button" key={id} className={barrier===id?'selected':''} onClick={()=>setBarrier(id)} aria-pressed={barrier===id}>{barriers[id].label}</button>)}</div><div className="setup-explain"><strong>Как это учтено</strong><p>{barriers[barrier].help}</p></div></>}
 {stage===3&&<><span className="eyebrow">Сегодняшний темп</span><h1>Сколько сил и времени?</h1><p className="setup-lead">Эти ответы помогают выбрать посильное действие сегодня. Их можно менять перед следующим шагом.</p><label className="control-label">Сколько сил?</label><div className="segmented">{([['low','Почти нет'],['medium','Нормально'],['high','Много']] as [Energy,string][]).map(([id,label])=><button key={id} className={energy===id?'active':''} onClick={()=>setEnergy(id)}>{label}</button>)}</div><label className="control-label">Сколько времени есть?</label><div className="segmented">{[[15,'15 мин'],[30,'30 мин'],[60,'1 час'],[120,'2 часа']].map(([value,label])=><button key={value} className={minutes===value?'active':''} onClick={()=>setMinutes(Number(value))}>{label}</button>)}</div><p className="setup-tip">Если план не помещается в этот отрезок, игра предложит подготовительный шаг. Это не считается завершением большого этапа.</p></>}
 {stage===4&&<><span className="eyebrow">Твой маршрут</span><h1>Вот куда ведут шаги.</h1><p className="setup-lead">Это рабочая версия плана, а не обещание результата. После каждого этапа можно изменить маршрут.</p>{desiredResult.trim()&&<div className="setup-reason"><span className="eyebrow">Желаемый результат</span><p>{desiredResult.trim()}</p></div>}{reason.trim()&&<div className="setup-reason"><span className="eyebrow">Почему это важно</span><p>{reason.trim()}</p></div>}<div className="preview-goals">{selected.map((id,i)=><section className="preview-goal" key={id}><span className="eyebrow">Направление 0{i+1}</span><h2>{goals[id].title}</h2><p>{goals[id].result}</p><ol>{goals[id].steps.map(step=><li key={step.mission}>{step.title}</li>)}</ol></section>)}</div><p className="setup-tip">Прежние записи и опыт останутся. Если ты выбрал новый маршрут, его этапы начнутся с начала.</p></>}
 </div><footer className="setup-actions">{stage===0&&<button className="button primary" onClick={next}>Выбрать цель <ArrowRight size={18}/></button>}{stage>0&&<button className="button text" onClick={back}><ChevronLeft size={17}/> Назад</button>}{stage>0&&stage<4&&<button className="button primary" onClick={next}>Дальше <ArrowRight size={17}/></button>}{stage===4&&<button className="button primary" onClick={finish}>Начать маршрут <ArrowRight size={17}/></button>}{onCancel&&<button className="button text setup-cancel" onClick={onCancel}>Оставить прежний план</button>}</footer></div></main>
}
